basePath: /v1
definitions:
  v1.doAuthResponse:
    properties:
      token:
        type: string
    type: object
  v1.doDeleteResponse:
    properties:
      Status:
        type: string
    type: object
  v1.doUploadResponse:
    properties:
      Status:
        type: string
    type: object
  v1.historyResponse:
    properties:
      History:
        items:
          $ref: '#/definitions/v1.historyResponseAsset'
        type: array
    type: object
  v1.historyResponseAsset:
    properties:
      assetName:
        type: string
      created:
        type: string
    type: object
  v1.response:
    properties:
      error:
        example: message
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Using a file manage service
  title: File manage service API
  version: "1.0"
paths:
  /asset/history:
    get:
      consumes:
      - application/json
      description: Show all file upload history
      operationId: history
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.historyResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Show history
      tags:
      - asset
  /auth:
    post:
      consumes:
      - application/json
      description: Auth a user
      operationId: auth
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.doAuthResponse'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.doAuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Auth
      tags:
      - auth
  /del-asset/:assetName:
    delete:
      consumes:
      - application/json
      description: Delete asset
      operationId: del-asset
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.doDeleteResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Delete asset
      tags:
      - asset
  /upload-asset/:assetName:
    post:
      consumes:
      - application/json
      description: Upload a data
      operationId: do-upload
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.doUploadResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Upload
      tags:
      - upload
swagger: "2.0"
